# Mock data for ComplianceIQ

SCENARIOS = {
    "A": {
        "name": "Clean Auto-Approval",
        "applicant": {
            "full_name": "Sarah Chen",
            "id_photo": "female",
            "date_of_birth": "1988-03-15",
            "nationality": "Canadian",
            "residency_status": "Canadian Citizen",
            "address": {
                "street": "42 Bay Street, Apt 7B",
                "city": "Toronto",
                "province": "Ontario",
                "postal_code": "M5J 2K9",
            },
            "application_type": "TFSA",
            "id_document": {
                "type": "Ontario Driver's License",
                "number": "W1234-56789-01234",
                "expiry_date": "2027-08-20",
                "issuing_province": "Ontario",
            },
            "id_match_status": "PERFECT_MATCH",
            "pep_indicator": False,
            "pep_details": None,
            "sanctions_flags": [],
            "sanctions_match_score": None,
            "behavioral_flags": [],
        },
        "extraction_confidence": 0.97,
        "expected_outcome": "AUTO_APPROVED",
    },
    "B": {
        "name": "Multi-Product Complexity",
        "applicant": {
            "full_name": "Marcus Williams",
            "id_photo": "male",
            "date_of_birth": "1992-11-08",
            "nationality": "Canadian",
            "residency_status": "Canadian Citizen",
            "address": {
                "street": "156 Laurier Avenue West",
                "city": "Ottawa",
                "province": "Ontario",
                "postal_code": "K1P 5J9",
            },
            "application_type": "Credit Card",
            "id_document": {
                "type": "Canadian Passport",
                "number": "AB1234567",
                "expiry_date": "2029-04-12",
                "issuing_country": "Canada",
            },
            "id_match_status": "MATCH",
            "pep_indicator": False,
            "pep_details": None,
            "sanctions_flags": [],
            "sanctions_match_score": None,
            "behavioral_flags": [
                "MULTIPLE_PRODUCT_APPLICATIONS_SAME_SESSION",
            ],
            "session_applications": ["Savings Account", "Credit Card", "Investment Account"],
        },
        "extraction_confidence": 0.94,
        "expected_outcome": "ESCALATED",
    },
    "C": {
        "name": "Sanctions Fuzzy Match",
        "applicant": {
            "full_name": "Viktor Petrov",
            "id_photo": "male",
            "date_of_birth": "1975-06-22",
            "birth_country": "Russia",
            "nationality": "Russian",
            "residency_status": "Permanent Resident",
            "address": {
                "street": "890 Granville Street",
                "city": "Vancouver",
                "province": "British Columbia",
                "postal_code": "V6Z 1K3",
            },
            "application_type": "RRSP",
            "id_document": {
                "type": "Permanent Resident Card",
                "number": "PR-987654321",
                "expiry_date": "2026-01-15",
                "issuing_country": "Canada",
            },
            "id_match_status": "MATCH",
            "pep_indicator": True,
            "pep_details": {
                "category": "Politically Exposed Person",
                "source_country": "Russia",
                "position": "Former government official",
            },
            "sanctions_flags": ["FUZZY_MATCH"],
            "sanctions_match_score": 0.72,
            "sanctions_match_reference": "Viktor V. Petrov",
            "behavioral_flags": [],
        },
        "extraction_confidence": 0.91,
        "expected_outcome": "ESCALATED_HIGH_RISK",
    },
}
